# Generated by Django 5.1.2 on 2024-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='blogimage'),
        ),
    ]
